### ISSUE TITLE
how to fix 

### ISSUE THREAD

**Issue by tuantabit** [aston668334/nodepay-socks-python#2]
<img width="804" alt="x1" src="https://github.com/aston668334/nodepay-socks-python/assets/29135823/a51f9263-294a-4166-8377-0635dc58be16">
<img width="804" alt="x1" src="https://github.com/aston668334/nodepay-socks-python/assets/29135823/a51f9263-294a-4166-8377-0635dc58be16">

Traceback (most recent call last):
  File "D:\Script Nodepay\nodepay-socks-python-main\test.py", line 167, in <module>
    asyncio.run(main())
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 646, in run_until_complete     
    return future.result()
  File "D:\Script Nodepay\nodepay-socks-python-main\test.py", line 153, in main
    signals = (signal.SIGHUP, signal.SIGTERM, signal.SIGINT)
AttributeError: module 'signal' has no attribute 'SIGHUP'

**Comment by tuantadev** [comment]
done
